# Generated by Django 4.1.4 on 2022-12-18 23:55

from django.db import migrations, models
import markdownfield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('original_title', models.CharField(blank=True, max_length=255, null=True)),
                ('author', models.CharField(max_length=255)),
                ('lyrics', markdownfield.models.MarkdownField(rendered_field='rendered_lyrics')),
                ('rendered_lyrics', markdownfield.models.RenderedMarkdownField()),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
