# Generated by Django 4.1.4 on 2022-12-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Speaker",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="uploads/speakers/")),
                ("priority", models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                "ordering": ["-priority"],
            },
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("start_date", models.DateTimeField()),
                ("finish_date", models.DateTimeField()),
                ("priority", models.PositiveSmallIntegerField(default=1)),
                ("speakers", models.ManyToManyField(to="speeches.speaker")),
            ],
            options={
                "ordering": ["start_date", "-priority"],
            },
        ),
    ]
